### ISSUE TITLE
Unresolved external symbols even with imported lib

### ISSUE THREAD

**Issue by Karbust** [SerialKeyManager/SKM-Client-API-CPP#12] opened 2021-11-18 17:41 UTC
I'm trying to setup Cryptolens on a C++ Static Lib.
I build cryptolens lib with MT and MTd for x86.

I'm importing on the library like this:
```c++
#ifdef _DEBUG
#pragma comment(lib, "Cryptolens_Debug.lib")
#else
#pragma comment(lib, "Cryptolens_Release.lib")
#endif
```

Also tried to import on the main app on the linker, nothing seems to be working.

This are the errors (if I omit the lib import from above I get many more errors):
![image](https://user-images.githubusercontent.com/20361229/142467603-2a284c86-3c96-4780-902b-cb83265e2455.png)

The example applications work with the lib I compiled.

**Comment by svedi** [comment] 2021-11-29 07:19
Sorry, I missed the notification for this issue. I will start looking into this. Do you have some minimal example that exhibits this issue?

**Comment by Karbust** [comment] 2021-11-29 09:44
Unfortunately, I don't have a minimal reproducible example. Like I said, the error only happens on my source code. I have tried the with the examples given on this repo and I have no linking errors.

**Comment by svedi** [comment] 2021-12-02 17:45
I have been working on reproducing this problem. Some examples are in the `static_lib` branch. It would be helpful if you could provide some additional information on the setup. Does "I'm trying to setup Cryptolens on a C++ Static Lib." mean that you are using our library in a static library? And that you then include this static library in another application? Or do you just mean that you are using MT(d)? 

Just to check, are you following the instructions at https://github.com/Cryptolens/cryptolens-cpp/blob/master/tutorials/add-to-project-windows.md ?

I managed to reproduce something similar when compiling a static library and including this in a main application, but not adding `Cryptolens.lib` as a dependency in the main application besides the static library.

**Comment by Karbust** [comment] 2021-12-02 17:54
Yes, I did follow the instructions provided.

My application and lib are MT/MTd. I also compiled cryptolens's lib as such.
I imported the cryptolens's lib on my application, tried the code on the example "Example_Activate" and I got the error described above. This was just a test step to see if it was anything wrong with the library I'm developing, there is where the license related code should be. On my lib I only included the headers, since I can't include cryptolens's lib on another lib.

The error above is weird, since it doesn't happen with the example's provided. I also checked the examples's lib imports and added all of them on my application, same errors...

**Comment by svedi** [comment] 2021-12-03 13:27
"I imported the cryptolens's lib on my application, tried the code on the example "Example_Activate" and I got the error described above."

Does this mean that you get the linker errors if you add the code to the application instead of the static library?

What version of Visual Studio and C++ are you using? Are you compiling our library with the same C++ version as your main project? Since you use the names `Cryptolens_Debug.lib` and `Cryptolens_Release.lib` above I guess you dont follow our instructions exactly but have moved and/or renamed the generated libraries to some other folder, does this seem correct? Since I dont think the library files should have these names when compiling the code solution in `vsprojects/`.

If you have the time, would it be possible to try to create a new project from scratch and add the same settings as your main project, and see if you can reproduce the error?

**Comment by Karbust** [comment] 2021-12-06 12:18
I was able to replicate it on a clean project:
![image](https://user-images.githubusercontent.com/20361229/144844086-d2979c67-ba08-42b5-b98e-9dd58a914c71.png)

Here is the project:
[TesteCryptolensCpp.zip](https://github.com/Cryptolens/cryptolens-cpp/files/7660657/TesteCryptolensCpp.zip)

I only edited the Debug configuration. The code is from `Example_Activate`.

I'm using Visual Studio 2019 16.11.6 and C++17. I removed the unused libraries I don't use from the linker (even with then the errors persisted).

The libs used were compiled from the code on this repository, the only changes were the name of the output build to include the configuration name (`Cryptolens_Debug.lib` and `Cryptolens_Release.lib` and from `MD`/`MDd` to `MT`/`MTd`).

Vcpkg enabled using static libraries and x86-windows-static triplet.

**Comment by svedi** [comment] 2021-12-06 14:08
Great, thanks, I will have a look. Just a quick check, have you changed so you compile our library with C++17? If not, could you try doing that?

**Comment by Karbust** [comment] 2021-12-06 14:37
> Great, thanks, I will have a look. Just a quick check, have you changed so you compile our library with C++17? If not, could you try doing that?

Well, now I feel dumb, I hadn't tried that yet, but it worked. Shouldn't it work with C++14 anyway? Thank you

**Comment by svedi** [comment] 2021-12-06 15:01
Unfortunatly the C++ ABI varies with the implementations, and can change between different versions of compilers and different C++ standards used, making things a bit tricky :-(

I'll close this issue since if I understood correctly it's working now.

**Closed as completed by svedi** 2021-12-06 15:01 UTC
